encoding: utf-8

# SEO相关信息
title: TMaize Blog
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2016 皖ICP备16016174号'

# 路径配置
domainUrl: 'http://blog.tmaize.net'
baseUrl: ''

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Chat
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ["CNAME", "README.md", "build-tool"]