encoding: utf-8

# SEO相关信息
title: 中勤管理咨询有限公司
description: 中勤管理咨询有限公司
keywords: 中勤,中勤管理,咨询,财务,注册,注销,公司
author: 中勤管理咨询有限公司
footerText: 'Copyright © 2019 深圳市中勤管理咨询有限公司'

# 路径配置
domainUrl: 'http://blog.tmaize.net'
baseUrl: ''

# 菜单
menu:
  - title: 主页
    url: /
  - title: 注册业务
    url: /pages/categories.html
  - title: 变更业务
    url: /pages/search.html
  - title: 注销业务
    url: /pages/links.html
  - title: 财务业务
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ["CNAME", "README.md", "build-tool"]