# Site title
title: "@jasonrudolph"

# A description of your site for social meta tag and search engines
description: "Jason Rudolph - Programmer, consultant, speaker, and author specializing in Ruby and Rails"

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://jasonrudolph.com"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ""

# The site cover image on the home page
image:

# The shortname for your Disqus site to enable comments
disqus_shortname:

# Your Google Analytics tracking code
google_analytics_tracking_id: "UA-4605088-1"

# Site navigation
nav:
  - title: "Home"
    url:   "/"
  - title: "Talks"
    url:   "/events"
  - title: "About"
    url:   "/about"

# Author information
author:
  name: Jason Rudolph
  bio: Engineer at GitHub, runner, world traveler, and aspiring cookist
  avatar: /images/jasonrudolph.jpg

# The "read next" posts to recommend at the bottom of each post
recommended_posts:
  - url: /blog/2014/03/02/defining-atom-commands-in-your-init-script/
  - url: /blog/2013/01/23/as-creative-as-we-make-time-to-be/
  - url: /blog/2011/08/09/programming-achievements-how-to-level-up-as-a-developer/
  - url: /blog/2009/05/27/git-up-10-reasons-to-upgrade-your-old-git-installation/
  - url: /blog/2008/06/17/testing-anti-patterns-incidental-coverage/
  - url: /blog/2012/09/11/clojurescript-4-things-that-might-worry-you-but-should-not/

# Extra Open Graph and Twitter Cards settings for social sharing

# Fallback og:image when no page.image or site.image. Facebook requires image be
# at least 200 x 200 pixels.
og_image:

# twitter:site. Your Twitter username without "@"
twitter_site: jasonrudolph

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
